### ISSUE TITLE
Invalid Yaml from StatefulSet Helm template

### ISSUE THREAD

**Issue by JeffreyDD** [emberstack/docker-azure-pipelines-agent#15]
Environment: 
- Chart 2.1.4
- Helm 3.7.1
- Kubernetes v1.21.5+k3s2 (on k3s)

While deploying the helm chart I was prompted with the following error:
```
Error: parse error at (azure-pipelines-agent/templates/statefulset.yaml:87): unexpected EOF
helm.go:88: [debug] parse error at (azure-pipelines-agent/templates/statefulset.yaml:87): unexpected EOF
```

It appears the  `{{- if .Values.image.tag }}` in
https://github.com/emberstack/docker-azure-pipelines-agent/blob/c05ebc1f68d71f54d1394bef482d208eeb711d82/src/helm/azure-pipelines-agent/templates/statefulset.yaml#L45 is never closed, resulting in invalid Yaml. After removing this line Helm is able to properly template the charts' resources.

**Comment by winromulus** [comment]
Thanks @JeffreyDD for pointing it out. This was a merge relic
